### ISSUE TITLE
Where can I download trace.txt

### ISSUE THREAD

**Issue by traddo** [bogireddytejareddy/ushapelet-python#1]
In the https://sites.google.com/site/ushapelet/ I found the original code and data, but only the trace. TXT format confusion and error data is read.
What is the shape of this data？

**Comment by bogireddytejareddy** [comment]
First, I have downloaded UCR Time Series Dataset from the official website. Then, I combined Train and Test files to create a new .txt for each dataset.

Note: "I found the original code and data, but only the trace" This is because they are not seperated by commas.
